[meta_data]
updated_on = 2023-07-24

[content]
pruefidentifikatoren = [
    "11001",
    "11002",
    "11003",
    "11004",
    "11005",
    "11006",
    "11007",
    "11008",
    "11009",
    "11010",
    "11011",
    "11012",
    "11013",
    "11014",
    "11015",
    "11016",
    "11017",
    "11018",
    "11019",
    "11020",
    "11021",
    "11022",
    "11023",
    "11024",
    "11035",
    "11036",
    "11037",
    "11038",
    "11039",
    "11040",
    "11041",
    "11042",
    "11043",
    "11044",
    "11051",
    "11052",
    "11053",
    "11060",
    "11062",
    "11063",
    "11064",
    "11065",
    "11066",
    "11067",
    "11069",
    "11070",
    "11071",
    "11072",
    "11073",
    "11074",
    "11075",
    "11076",
    "11077",
    "11078",
    "11079",
    "11080",
    "11081",
    "11082",
    "11083",
    "11084",
    "11085",
    "11086",
    "11087",
    "11088",
    "11089",
    "11090",
    "11091",
    "11092",
    "11093",
    "11094",
    "11095",
    "11101",
    "11102",
    "11103",
    "11104",
    "11105",
    "11106",
    "11107",
    "11108",
    "11109",
    "11110",
    "11111",
    "11112",
    "11113",
    "11115",
    "11116",
    "11117",
    "11119",
    "11120",
    "11121",
    "11123",
    "11124",
    "11126",
    "11127",
    "11133",
    "11134",
    "11135",
    "11136",
    "11137",
    "11138",
    "11139",
    "11140",
    "11142",
    "11143",
    "11145",
    "11146",
    "11147",
    "11148",
    "11149",
    "11150",
    "11151",
    "11152",
    "11153",
    "11154",
    "11155",
    "11156",
    "11157",
    "11159",
    "11160",
    "11161",
    "11162",
    "11163",
    "11164",
    "11165",
    "11166",
    "11167",
    "11168",
    "11169",
    "11170",
    "11171",
    "11172",
    "11173",
    "11174",
    "11175",
    "11176",
    "11177",
    "11178",
    "11180",
    "11181",
    "11182",
    "11185",
    "11186",
    "11187",
    "11188",
    "11189",
    "11190",
    "11191",
    "11192",
    "11193",
    "11194",
    "11195",
    "11196",
    "11197",
    "11198",
    "11199",
    "11200",
    "11201",
    "11202",
    "11203",
    "11204",
    "11205",
    "11206",
    "11207",
    "11208",
    "11209",
    "11210",
    "11211",
    "11212",
    "11213",
    "11214",
    "11215",
    "11216",
    "11217",
    "11218",
    "11219",
    "11220",
    "11221",
    "11222",
    "11223",
    "11224",
    "11225",
    "11226",
    "11227",
    "11228",
    "11229",
    "11230",
    "11231",
    "11232",
    "11233",
    "11234",
    "13002",
    "13003",
    "13005",
    "13006",
    "13007",
    "13008",
    "13009",
    "13010",
    "13011",
    "13012",
    "13013",
    "13014",
    "13015",
    "13016",
    "13017",
    "13018",
    "13019",
    "13020",
    "13021",
    "13022",
    "13023",
    "13025",
    "13026",
    "13027",
    "15001",
    "15002",
    "15003",
    "15004",
    "17001",
    "17002",
    "17003",
    "17004",
    "17005",
    "17006",
    "17007",
    "17008",
    "17009",
    "17101",
    "17102",
    "17103",
    "17104",
    "17110",
    "17113",
    "17114",
    "17115",
    "17116",
    "17117",
    "17118",
    "17119",
    "17120",
    "17121",
    "17122",
    "17123",
    "17126",
    "17127",
    "17128",
    "17129",
    "17130",
    "17131",
    "17201",
    "17202",
    "17203",
    "17204",
    "17205",
    "17206",
    "17207",
    "17208",
    "17209",
    "17210",
    "17211",
    "17301",
    "19001",
    "19002",
    "19003",
    "19004",
    "19005",
    "19006",
    "19007",
    "19008",
    "19009",
    "19010",
    "19011",
    "19012",
    "19013",
    "19014",
    "19015",
    "19016",
    "19101",
    "19102",
    "19103",
    "19104",
    "19110",
    "19114",
    "19115",
    "19116",
    "19117",
    "19118",
    "19119",
    "19120",
    "19121",
    "19122",
    "19123",
    "19124",
    "19127",
    "19128",
    "19129",
    "19130",
    "19131",
    "19132",
    "19204",
    "19301",
    "19302",
    "21000",
    "21001",
    "21002",
    "21003",
    "21004",
    "21005",
    "21007",
    "21009",
    "21010",
    "21011",
    "21012",
    "21013",
    "21015",
    "21018",
    "21024",
    "21025",
    "21026",
    "21027",
    "21028",
    "21029",
    "21030",
    "21031",
    "21032",
    "21033",
    "21034",
    "21035",
    "21036",
    "21037",
    "21038",
    "21039",
    "21040",
    "21041",
    "21042",
    "21043",
    "21044",
    "25001",
    "25002",
    "25003",
    "25004",
    "25005",
    "25006",
    "25007",
    "25008",
    "25009",
    "27001",
    "27002",
    "27003",
    "29001",
    "29002",
    "31001",
    "31002",
    "31003",
    "31004",
    "31005",
    "31006",
    "31007",
    "31008",
    "31009",
    "31010",
    "31011",
    "33001",
    "33002",
    "33003",
    "33004",
    "35001",
    "35002",
    "35003",
    "35004",
    "37000",
    "37001",
    "37002",
    "37003",
    "37004",
    "37005",
    "37006",
    "37007",
    "39000",
    "39001",
    "39002",
    "44001",
    "44002",
    "44003",
    "44004",
    "44005",
    "44006",
    "44007",
    "44008",
    "44009",
    "44010",
    "44011",
    "44012",
    "44013",
    "44014",
    "44015",
    "44016",
    "44017",
    "44018",
    "44019",
    "44020",
    "44021",
    "44022",
    "44023",
    "44024",
    "44035",
    "44036",
    "44037",
    "44038",
    "44039",
    "44040",
    "44041",
    "44042",
    "44043",
    "44044",
    "44051",
    "44052",
    "44053",
    "44060",
    "44101",
    "44102",
    "44103",
    "44104",
    "44105",
    "44109",
    "44111",
    "44112",
    "44113",
    "44115",
    "44116",
    "44117",
    "44119",
    "44120",
    "44121",
    "44123",
    "44124",
    "44137",
    "44138",
    "44139",
    "44140",
    "44142",
    "44143",
    "44145",
    "44146",
    "44147",
    "44148",
    "44149",
    "44150",
    "44151",
    "44152",
    "44156",
    "44157",
    "44159",
    "44160",
    "44161",
    "44162",
    "44163",
    "44164",
    "44165",
    "44166",
    "44167",
    "44168",
    "44169",
    "44170",
    "44175",
    "44176",
    "44180",
    "44181",
    "44182",
    "55001",
    "55002",
    "55003",
    "55004",
    "55005",
    "55006",
    "55007",
    "55008",
    "55009",
    "55010",
    "55011",
    "55012",
    "55013",
    "55014",
    "55015",
    "55016",
    "55017",
    "55018",
    "55022",
    "55023",
    "55024",
    "55035",
    "55036",
    "55037",
    "55038",
    "55039",
    "55040",
    "55041",
    "55042",
    "55043",
    "55044",
    "55051",
    "55052",
    "55053",
    "55060",
    "55062",
    "55063",
    "55064",
    "55065",
    "55066",
    "55067",
    "55069",
    "55070",
    "55071",
    "55072",
    "55073",
    "55074",
    "55075",
    "55076",
    "55077",
    "55078",
    "55079",
    "55080",
    "55081",
    "55082",
    "55083",
    "55084",
    "55085",
    "55086",
    "55087",
    "55088",
    "55089",
    "55090",
    "55091",
    "55092",
    "55093",
    "55094",
    "55095",
    "55101",
    "55102",
    "55103",
    "55104",
    "55105",
    "55106",
    "55107",
    "55108",
    "55109",
    "55110",
    "55111",
    "55112",
    "55113",
    "55115",
    "55116",
    "55117",
    "55119",
    "55120",
    "55121",
    "55123",
    "55124",
    "55126",
    "55127",
    "55133",
    "55134",
    "55135",
    "55136",
    "55137",
    "55138",
    "55139",
    "55140",
    "55142",
    "55143",
    "55145",
    "55146",
    "55147",
    "55148",
    "55149",
    "55150",
    "55151",
    "55152",
    "55153",
    "55154",
    "55155",
    "55156",
    "55157",
    "55159",
    "55160",
    "55161",
    "55162",
    "55163",
    "55164",
    "55165",
    "55166",
    "55167",
    "55168",
    "55169",
    "55170",
    "55171",
    "55172",
    "55173",
    "55174",
    "55175",
    "55176",
    "55177",
    "55178",
    "55180",
    "55181",
    "55182",
    "55185",
    "55186",
    "55187",
    "55188",
    "55189",
    "55190",
    "55191",
    "55192",
    "55193",
    "55194",
    "55195",
    "55196",
    "55197",
    "55198",
    "55199",
    "55200",
    "55201",
    "55202",
    "55203",
    "55204",
    "55205",
    "55206",
    "55207",
    "55208",
    "55209",
    "55210",
    "55211",
    "55212",
    "55213",
    "55214",
    "55215",
    "55216",
    "55217",
    "55218",
    "55219",
    "55220",
    "55221",
    "55222",
    "55223",
    "55224",
    "55225",
    "55226",
    "55227",
    "55228",
    "55229",
    "55230",
    "55231",
    "55232",
    "55233",
    "55234",
    "55235",
    "55236",
    "55237",
    "55238",
    "55239",
    "55240",
    "55241",
    "55242",
    "55243",
    "55553",
    "55554",
    "55555",
    "55556"
]
